Improve Heap extraction performance
singer-io/tap-heap pull request #20
Opened 2024-07-09 17:43 UTC by RushiT0122

# Description of change
- Improve the extraction performance by adding multi-processing.
- Improve logging

# Manual QA steps
 - Tested changes on the cloned connection.
 - Conducted performance testing to determine the optimal number of threads.
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2024-07-09 18:04 UTC, longestpath requested changes
Just some typos, seems solid as long as it was proven in practice

2024-07-09 18:04 UTC, longestpath commented on tap_heap/sync.py
> +    LOGGER.info("Found %d menifest files.", len(files))
```suggestion
    LOGGER.info("Found %d manifest files.", len(files))
```

2024-07-09 18:04 UTC, longestpath commented on tap_heap/sync.py
> +# This event will signal all producer and consumer threads to stop thier execution
```suggestion
# This event will signal all producer and consumer threads to stop their execution
```

2024-07-09 18:04 UTC, longestpath commented on tap_heap/sync.py
> +    LOGGER.info("Existing from the consumer thread!")
```suggestion
    LOGGER.info("Exiting from the consumer thread!")
```

2024-07-09 18:04 UTC, longestpath commented on tap_heap/sync.py
> +            LOGGER.info("Extracted %d/%d menifest files.", i + batch_size, len(files))
```suggestion
            LOGGER.info("Extracted %d/%d manifest files.", i + batch_size, len(files))
```

2024-07-09 18:04 UTC, longestpath commented on tap_heap/sync.py
> +                    raise ProcessError("Recieved event to terminate the thread abruptly!")
```suggestion
                    raise ProcessError("Received event to terminate the thread abruptly!")
```

2024-07-09 18:35 UTC, RushiT0122 commented on tap_heap/sync.py
> +    LOGGER.info("Found %d menifest files.", len(files))
Fixed

2024-07-09 18:35 UTC, RushiT0122 commented on tap_heap/sync.py
> +# This event will signal all producer and consumer threads to stop thier execution
Fixed

2024-07-09 18:35 UTC, RushiT0122 commented on tap_heap/sync.py
> +    LOGGER.info("Existing from the consumer thread!")
Fixed

2024-07-09 18:36 UTC, RushiT0122 commented on tap_heap/sync.py
> +            LOGGER.info("Extracted %d/%d menifest files.", i + batch_size, len(files))
Fixed

2024-07-09 18:36 UTC, RushiT0122 commented on tap_heap/sync.py
> +                    raise ProcessError("Recieved event to terminate the thread abruptly!")
Fixed

2024-07-09 20:45 UTC, dmosorast requested changes
Would it be possible to get the tests passing before merging? It's been awhile since a change was made to this repo, so it'd be good to make sure the unit tests still pass.

2024-07-10 13:23 UTC, dmosorast approved these changes

2024-07-11 14:29 UTC, merged